library(CRF)
data(TestFunc)

cat("Testing dataset Small ...\n")
data(Small)
test.infer("Exact", infer.exact, small.crf, small.answer)
test.infer("Chain", infer.chain, small.crf, small.answer)
test.infer("Tree", infer.tree, small.crf, small.answer)
test.infer("Cutset", infer.cutset, small.crf, small.answer, 1e-8, c(3))
test.infer("Cutset (Chain)", infer.cutset, small.crf, small.answer, 1e-8, c(1), "chain")
test.infer("JunctionTree", infer.junction, small.crf, small.answer)
test.infer("Sample", infer.sample, small.crf, small.answer, 1e-2, sample.exact, 1000000)
test.infer("LBP", infer.lbp, small.crf, small.answer)
test.infer("TRBP", infer.trbp, small.crf, small.answer)

cat("Testing dataset Chain ...\n")
data(Chain)
test.infer("Chain", infer.chain, chain.crf, chain.answer)
test.infer("Tree", infer.tree, chain.crf, chain.answer)
test.infer("Cutset", infer.cutset, chain.crf, chain.answer, 1e-8, c(3))
test.infer("Cutset (Chain)", infer.cutset, chain.crf, chain.answer, 1e-8, c(1), "chain")
test.infer("JunctionTree", infer.junction, chain.crf, chain.answer)
test.infer("Sample", infer.sample, chain.crf, chain.answer, 1e-2, sample.chain, 1000000)
test.infer("LBP", infer.lbp, chain.crf, chain.answer)
test.infer("TRBP", infer.trbp, chain.crf, chain.answer)

cat("Testing dataset Tree ...\n")
data(Tree)
test.infer("Tree", infer.tree, tree.crf, tree.answer)
test.infer("Cutset", infer.cutset, tree.crf, tree.answer, 1e-8, c(3))
test.infer("JunctionTree", infer.junction, tree.crf, tree.answer)
test.infer("Sample", infer.sample, tree.crf, tree.answer, 1e-2, sample.tree, 1000000)
test.infer("LBP", infer.lbp, tree.crf, tree.answer)
test.infer("TRBP", infer.trbp, tree.crf, tree.answer)

cat("Testing dataset Loop ...\n")
data(Loop)
test.infer("Cutset", infer.cutset, loop.crf, loop.answer, 1e-8, c(3))
test.infer("Cutset (Chain)", infer.cutset, loop.crf, loop.answer, 1e-8, c(1), "chain")
test.infer("JunctionTree", infer.junction, loop.crf, loop.answer, 0.01)
test.infer("Sample", infer.sample, loop.crf, loop.answer, 1e-2, sample.exact, 1000000)
test.infer("LBP", infer.lbp, loop.crf, loop.answer, 0.01)
test.infer("TRBP", infer.trbp, loop.crf, loop.answer, 0.1)

cat("Testing dataset Clique ...\n")
data(Clique)
test.infer("Cutset", infer.cutset, clique.crf, clique.answer, 1e-8, c(1,3))
test.infer("JunctionTree", infer.junction, clique.crf, clique.answer, 0.1)
test.infer("Sample", infer.sample, clique.crf, clique.answer, 1e-2, sample.exact, 1000000)
test.infer("LBP", infer.lbp, clique.crf, clique.answer, 0.1)
test.infer("TRBP", infer.trbp, clique.crf, clique.answer, 0.1)
