library(CRF)
data(TestFunc)

cat("Testing dataset Small ...\n")
data(Small)
test.decode("Exact", decode.exact, small.crf, small.answer)
test.decode("Chain", decode.chain, small.crf, small.answer)
test.decode("Tree", decode.tree, small.crf, small.answer)
test.decode("Cutset", decode.cutset, small.crf, small.answer, c(3))
test.decode("CutsetChain", decode.cutsetChain, small.crf, small.answer, c(1))
test.decode("Sample", decode.sample, small.crf, small.answer, sample.exact, 10000)
test.decode("LBP", decode.lbp, small.crf, small.answer)
test.decode("TRBP", decode.trbp, small.crf, small.answer)

cat("Testing dataset Chain ...\n")
data(Chain)
test.decode("Chain", decode.chain, chain.crf, chain.answer)
test.decode("Tree", decode.tree, chain.crf, chain.answer)
test.decode("Cutset", decode.cutset, chain.crf, chain.answer, c(3))
test.decode("CutsetChain", decode.cutsetChain, chain.crf, chain.answer, c(1))
test.decode("Sample", decode.sample, chain.crf, chain.answer, sample.chain, 10000)
test.decode("LBP", decode.lbp, chain.crf, chain.answer)
test.decode("TRBP", decode.trbp, chain.crf, chain.answer)

cat("Testing dataset Tree ...\n")
data(Tree)
test.decode("Tree", decode.tree, tree.crf, tree.answer)
test.decode("Cutset", decode.cutset, tree.crf, tree.answer, c(3))
test.decode("Sample", decode.sample, tree.crf, tree.answer, sample.tree, 10000)
test.decode("LBP", decode.lbp, tree.crf, tree.answer)
test.decode("TRBP", decode.trbp, tree.crf, tree.answer)

cat("Testing dataset Loop ...\n")
data(Loop)
test.decode("Cutset", decode.cutset, loop.crf, loop.answer, c(3))
test.decode("CutsetChain", decode.cutsetChain, loop.crf, loop.answer, c(1))
test.decode("Sample", decode.sample, loop.crf, loop.answer, sample.exact, 10000)
test.decode("LBP", decode.lbp, loop.crf, loop.answer)
test.decode("TRBP", decode.trbp, loop.crf, loop.answer)

cat("Testing dataset Clique ...\n")
data(Clique)
test.decode("Cutset", decode.cutset, clique.crf, clique.answer, c(1,3))
test.decode("Sample", decode.sample, clique.crf, clique.answer, sample.exact, 10000)
test.decode("LBP", decode.lbp, clique.crf, clique.answer)
test.decode("TRBP", decode.trbp, clique.crf, clique.answer)
