library(CRF)
data(TestFunc)

cat("Testing dataset Small ...\n")
data(Small)
test.sample("Exact", sample.exact, small.crf, small.answer)
test.sample("Chain", sample.chain, small.crf, small.answer)
test.sample("Tree", sample.tree, small.crf, small.answer)
test.sample("Cutset", sample.cutset, small.crf, small.answer, 0.01, 10000, c(3))
test.sample("Cutset (Chain)", sample.cutset, small.crf, small.answer, 0.01, 10000, c(1), "chain")
test.sample("JunctionTree", sample.junction, small.crf, small.answer)
test.sample("Gibbs", sample.gibbs, small.crf, small.answer, 0.01, 1000000, 10000)

cat("Testing dataset Chain ...\n")
data(Chain)
test.sample("Chain", sample.chain, chain.crf, chain.answer)
test.sample("Tree", sample.tree, chain.crf, chain.answer)
test.sample("Cutset", sample.cutset, chain.crf, chain.answer, 0.01, 10000, c(3))
test.sample("Cutset (Chain)", sample.cutset, chain.crf, chain.answer, 0.01, 10000, c(1), "chain")
test.sample("JunctionTree", sample.junction, chain.crf, chain.answer)
test.sample("Gibbs", sample.gibbs, chain.crf, chain.answer, 0.01, 1000000, 10000)

cat("Testing dataset Tree ...\n")
data(Tree)
test.sample("Tree", sample.tree, tree.crf, tree.answer)
test.sample("Cutset", sample.cutset, tree.crf, tree.answer, 0.01, 10000, c(3))
test.sample("JunctionTree", sample.junction, tree.crf, tree.answer)
test.sample("Gibbs", sample.gibbs, tree.crf, tree.answer, 0.01, 1000000, 10000)

cat("Testing dataset Loop ...\n")
data(Loop)
test.sample("Cutset", sample.cutset, loop.crf, loop.answer, 0.01, 10000, c(1,3))
test.sample("Cutset (Chain)", sample.cutset, loop.crf, loop.answer, 0.01, 10000, c(1), "chain")
test.sample("JunctionTree", sample.junction, loop.crf, loop.answer)
test.sample("Gibbs", sample.gibbs, loop.crf, loop.answer, 0.01, 1000000, 10000)

cat("Testing dataset Clique ...\n")
data(Clique)
test.sample("Cutset", sample.cutset, clique.crf, clique.answer, 0.01, 10000, c(1,3))
test.sample("JunctionTree", sample.junction, clique.crf, clique.answer)
test.sample("Gibbs", sample.gibbs, clique.crf, clique.answer, 0.01, 1000000, 10000)
